import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { Space_Grotesk } from "next/font/google";
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
});

import { MarketTicker } from '@/components/dashboard/MarketTicker';
import { Navigation } from '@/components/Navigation';
import { BackgroundManager } from '@/components/BackgroundManager';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} h-full antialiased dark`}>
      <body className="min-h-full flex flex-col bg-[#0A0A0A] relative selection:bg-[#E8FF5A]/30 font-space text-white">
        <BackgroundManager />
        <div className="flex-1 pb-10 pt-20">
          <Navigation />
          {children}
        </div>
        <MarketTicker />
        <Toaster theme="dark" />
      </body>
    </html>
  );
}
